name: C++ CI

# on the following actions perform the specified operations
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Build project
      run: |
        cd project
        chmod +x ./build.sh
        ./build.sh
    
    - name: Run tests inside the build folder
      run: |
        cd project/build
        ./test_multiplication


    - name: Install Singularity
      run: |
        sudo apt-get update && sudo apt-get install -y \
            build-essential \
            uuid-dev \
            libgpgme-dev \
            squashfs-tools \
            libseccomp-dev \
            wget \
            pkg-config \
            git \
            cryptsetup

        export VERSION=4.1.3 && # adjust this as necessary \
        wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz \
        && tar -xzf singularity-${VERSION}.tar.gz \
        && cd singularity-${VERSION} \
        && ./mconfig \
        && make -C builddir \
        && sudo make -C builddir install

    - name: Build Singularity container
      run: |
        sudo singularity build my_project.sif Singularity.def



