name: C++ CI

Copy code
# on the following actions perform the specified operations
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Build project
      run: |
        chmod +x ./build.sh
        ./build.sh
    
    - name: Run tests inside the build folder
      run: |
        cd build
        ./test_multiplication

    # - name: Configure CMake
    #   run: cmake -S . -B build

    # - name: Build
    #   run: cmake --build build

    # - name: Run Tests
    #   run: ctest --test-dir build


