name: C++ CI

# on the following actions perform the specified operations
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Build project
      run: |
        cd project
        chmod +x ./build.sh
        ./build.sh
    
    - name: Run tests inside the build folder
      run: |
        cd build
        ./test_multiplication

    - name: Install Singularity
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container

    - name: Build Singularity container
      run: |
        sudo singularity build my_project.sif Singularity.def

    # - name: Upload Singularity container to GitHub artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my_project_container
    #     path: my_project.sif


